complete-ruby-on-rails-developer-course-udemy/finance_tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/models/stock.rb
class Stock < ApplicationRecord
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iexcloud[:publishable_token],
      secret_token:  Rails.application.credentials.iexcloud[:secret_token],
      endpoint: 'https://cloud.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol , name: 'Company name', last_price: client.quote(ticker_symbol).latest_price)
    rescue => exception
      return nil
    end
      # client.quote(ticker_symbol).latest_price
  end
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
      #   respond_to do |format|
      #     format.js { render partial: 'users/result' }
      #   end
      # Update to use rails turbo frame to render the result here?
        render 'users/my_portfolio'
      else
        flash[:alert] = "Stock not found"
        render 'users/my_portfolio'
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/helpers/users_helper.rb
module UsersHelper
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/helpers/welcome_helper.rb
module WelcomeHelper
end

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Finance Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <% if !current_user %>
        <li class="nav-item">
          <a class="nav-link" href="/signin">Sign in</a>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }  %>
          </li>
        <% end %>
    </div>
  </div>
</nav>

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render('layouts/navigation') %>
    <div class="container">
      <%= render('layouts/messages') %>
      <%= yield %>
    </div>
  </body>
</html>

complete-ruby-on-rails-developer-course-udemy/finance_tracker/app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area"> 
  <p>Search stocks</p>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form-group row">
  <div class="col-sm-9">
    <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: 'form-control form-control-large' %>
  </div>
  <div class="col-sm-3">
    <%= button_tag type: :submit, class: 'btn btn-success' do %>
      <%= 'Search' %>
    <% end %>
  </div>
  </div>
  <% end %>
</div>

<% if @stock %>
  <div class="card card-header">
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Company name: </strong><%= @stock.name %>
    <strong>Last price: </strong><%= @stock.last_price %>
  </div>
<% end %>