complete-ruby-on-rails-developer-course-udemy/message_me/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'message', to: 'messages#create'
end

complete-ruby-on-rails-developer-course-udemy/message_me/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(10) }
end

complete-ruby-on-rails-developer-course-udemy/message_me/app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 15 }
  has_secure_password
  has_many :messages
end

complete-ruby-on-rails-developer-course-udemy/message_me/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  def destroy
    flash[:notice] = "Logged out"
    session[:user_id] = nil
    redirect_to root_path
  end
end

complete-ruby-on-rails-developer-course-udemy/message_me/app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

complete-ruby-on-rails-developer-course-udemy/message_me/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast("chatroom_channel", { mod_message: message_render(message) })
    end
  end

  private 

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

complete-ruby-on-rails-developer-course-udemy/message_me/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      flash[:notice] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "there was something wrong with your login details" # flash.now without showing on redirect
      render 'new'
    end
  end

  private
  def logged_in_redirect
    if logged_in?
      flash[:error] = "you are already logged in"
      redirect_to root_path
    end
  end

end

complete-ruby-on-rails-developer-course-udemy/message_me/app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular inverted teal coffee icon"></i>
  Chat App
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui small feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: 'ui reply form'}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, id: 'message_body' %>
              <%= f.button '<i class="bordered inverted teal edit icon"></i>'.html_safe%>
            </div>
          </div>
        <% end %>
        </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui vertical menu">
          <a class="active teal item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

complete-ruby-on-rails-developer-course-udemy/message_me/app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

complete-ruby-on-rails-developer-course-udemy/message_me/app/views/layouts/_navigation.html.erb
<div class="ui mini inverted menu">
  <div class="ui container">
    <a class="item" href="/">
      Home
    </a>
    <a class="item" href="/">
      Messages
    </a>
    <a class="item">
      English
    </a>
    <a class="item">
      Russian
    </a>
    <a class="item">
      Spanish
    </a>
    <% if logged_in? %>
      <a class="item">
        My Profile
      </a>
      <%= link_to "Logout", logout_path, class: 'item', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }%>    <% else %>
      <a class="item" href="/login">
        Sign up
      </a>
    <% end %>
  </div>
</div>

complete-ruby-on-rails-developer-course-udemy/message_me/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>