complete-ruby-on-rails-developer-course-udemy/rails-app/config/routes.rb
Rails.application.routes.draw do  
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles # , only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { maximum: 25, minimum: 5}
  validates_uniqueness_of :name
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
                        uniqueness: {case_sensitive: false}, 
                        length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    length: {maximum: 105},
                    format: { with: VALID_EMAIL_REGEX}
  has_many :articles
  has_secure_password
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :is_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # memoization - only fetch from db if not already set
  end

  def logged_in?
    !!current_user # !! turns into boolean
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  def is_admin?
    logged_in? && current_user.admin == true
  end
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
    # Article.all
  end

  def show
  end

  def new
    @article = Article.new()
  end

  def edit
  end

  def create
    # render plain: params[:article] # need data: { turbo: false } on form_with to work
    @article = Article.new(article_params)
    @article.user = current_user
    # render plain: @article.inspect # need data: { turbo: false } on form_with to work
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article # article_path(@article)
    else
      render 'new', status: 422
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else 
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user
      flash[:alert] = "you can only edit or delete your own article"
      redirect_to @article
    end
  end
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to @category
    else
      render "new"
    end
  end
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 2)
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "category updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "you must be logged in as an admin"
      redirect_to categories_path
    end
  end
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "there was something wrong with your login details" # flash.now without showing on redirect
      render 'new'
    end
  end

  def destroy
    flash[:notice] = "Logged out"
    session[:user_id] = nil
    redirect_to root_path
  end
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  # GET /users or /users.json
  def index
    @users =  User.paginate(page: params[:page], per_page: 2)
    # User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User was created successfully"
      redirect_to users_path
    else
      render 'new', status: 422
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully"
      redirect_to users_path
    else 
      render 'edit'
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user
        flash[:alert] = "you can only edit your own account"
        redirect_to @user
      end
    end
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/helpers/pages_helper.rb
module PagesHelper
end

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/articles/_article.html.erb
  <div class="card">
    <%# <div class="card-header">
      Featured
    </div> %>
    <div class="card-body">
      <h5 class="card-title"><%= article.title %></h5>
      <p class="card-text"><%= article.description %></p>
      <p class="card-text">Created by user: <%= article.user.username if article.user %></p>
      <%= link_to 'View', article_path(article) %> 
      <% if logged_in? && article.user == current_user %>
      | <%= link_to 'Edit', edit_article_path(article) %> | <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }%>
      <% end %>
    </div>
  </div>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/articles/_form.html.erb
<%= render('shared/errors', obj: @article) %>

<%= form_with(model: @article, local: true)  do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
   <p>
    <%= f.label :category %><br/>
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<p><%= link_to 'Cancel and return to articles', articles_path %></p>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/articles/index.html.erb
<h1>Articles</h1>
<div class="text-center">

<%= will_paginate @articles %>

<% @articles.each do |article| %>
  <%= render 'articles/article', article: article %>
<% end %>

<%= will_paginate @articles %>

<p><%= link_to 'Create new article', new_article_path %></p>
</div>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<p><%= link_to 'Return to articles', articles_path %></p>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.description %></p>
<p>Created by user: <%= @article.user.username if @article.user %></p>
<% if @article.categories.any? %>
  <% @article.categories.each do |cat| %>
    <%= link_to cat.name, category_path(cat)%>
  <% end %>
<% end %>
<% if logged_in? && @article.user == current_user %>
  <p><%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> | <%= link_to 'Return to articles', articles_path %></p>
<% end %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/categories/_form.html.erb
<%= render('shared/errors', obj: @category) %>

<%= form_with(model: @category, local: true)  do |f| %>
  <p>
    <%= f.label :name, "Category name" %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/categories/edit.html.erb
<h1>Update category</h1>

<%= render 'form' %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/categories/index.html.erb
<h1>Categories</h1>
<div class="text-center">

<%= will_paginate @categories %>

<% @categories.each do |category| %>
  <a href="/categories/<%= category.id %>"><%= category.name %></a><br/>
  <%= pluralize(category.articles.count, "articles") %>
<% end %>

<%= will_paginate @categories %>

<% if logged_in? && current_user.admin? %>
  <p><%= link_to 'Create new category', new_category_path %></p>
<% end %>
</div>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/categories/new.html.erb
<h1>Create category</h1>

<%= render 'form' %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<h2><%= pluralize(@category.articles.count, "article") %></h2>
<% @category.articles.each do |article| %>
  <%= render 'articles/article', article: article %>
<% end %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/pages/about.html.erb
<h1>About page</h1>

<p><%= link_to 'Articles listing', articles_path %> | <%= link_to 'Home', root_path %></p>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white p-4">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to "Sign up!", signup_path, class: 'btn btn-success btn-lg' %>
    </div>
  </div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "ThisIsAmandine", 'https://thisisamandine.com', class: 'text-white'%></small>
  </div>
</footer>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/users/_form.html.erb
<%= render('shared/errors', obj: @user) %>

<%= form_with(model: @user, local: true)  do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>
  </p>
<% end %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/users/index.html.erb
<h1>Users</h1>
<div class="text-center">

<%= will_paginate @users %>

<% @users.each do |user| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= user.username %></h5>
      <p class="card-text"><%= user.email %></p>
      <%= link_to 'Show', user_path(user) %> | <%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Delete', user_path(user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }%>
    </div>
  </div>
<% end %>

<%= will_paginate @users %>

</div>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

complete-ruby-on-rails-developer-course-udemy/rails-app/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p><%= @user.email %></p>

<% if logged_in? && @user == current_user %>
  <p><%= link_to 'Edit', edit_user_path(@user) %> | <%= link_to 'Delete', user_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></p>
<% end %>

<h2>User's <%= pluralize(@user.articles.count, "article") %></h2>
<% @user.articles.each do |article| %>
  <%= render 'articles/article', article: article %>
<% end %>